### ISSUE TITLE
FindMergeCommits stops early

### ISSUE THREAD

**Issue by benedikt-schesch** [benedikt-schesch/AST-Merging-Evaluation#251]
It seems like FindMergeCommits terminates early. When you run `rm -rf results/merges` and then `sh run_full.sh` I only get 124 repos with merges out of the ~850 that should be there. Running the script ~5 times gives the full result but then I am not sure if the first runs are the full results or just partial results.

**Comment by mernst** [comment]
The problem is that both of these repositories:

k3po/k3po
kaazing/k3po

are contending for the same file name on disk: /scratch/mernst/ast-merge-eval-data/k3po .

I recall that I suggested putting both the owner and organization names in file names, as in

  /scratch/mernst/ast-merge-eval-data/k3po__k3po
  /scratch/mernst/ast-merge-eval-data/kaazing__k3po

I think we should revisit that suggestion.

**Comment by benedikt-schesch** [comment]
Ok perfect, I changed it such that it creates a dir `/scratch/mernst/ast-merge-eval-data/kaazing/k3po` and a dir `/scratch/mernst/ast-merge-eval-data/kaazing/k3po`. I prefer this clear separation between owner and project name.

**Comment by mernst** [comment]
OK.  I assume you did this throughout the codebase, not just for FindMegeCommits, or else we will get problems later in the pipeline.

**Comment by benedikt-schesch** [comment]
When cloning the repos we have `ownder/project_name` and then when we copy the repos it used to be a random name but you change it to `project_name+hash` which is unique, so we should be good on that.

**Comment by mernst** [comment]
The use of random names made debugging unnecessarily difficult.
`project_name+hash` is not unique, if one project is a fork of another, because hash might be on both forks (if it was committed before the fork was made).  It will be identical between the two projects, though.  I'm not sure whether this requires extra checks or not.

**Comment by benedikt-schesch** [comment]
I see, this might be a problem. The name is not `project_name+hash` it's `"left-" + left_sha + "-" + right_sha` which has the same technical problem. Doing `left_sha+right_sha+project_name+owner_name` is not legal though because the name is too long. I'll change the name to: 'owner/project_name/left+right sha`

**Comment by mernst** [comment]
OK, thanks.
